name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request

jobs:
  testing:
    name: Lint Check and Testing

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Change wrapper permissions  // 2
        run: chmod +x ./gradlew

      # Step 4: Yun your unit tests
      - name: Run Unit Tests
        run: bash ./gradlew test --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
