name: runOnGitHub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v1

      - name: Change wrapper permissions  // 2
          run: chmod +x ./gradlew

      - name: Run Tests                   // 3
          run: ./gradlew test

      - name: Build Project               // 4
          run: ./gradlew assemble